def print_a_number_between_zero_and_nine():
    digit = int(input("Enter a digit between 0 and 9: "))
    if digit == 1:
        print(" " * 3, "*")
        print(" " * 3, "*")
        print(" " * 3, "*")
        print()
        print(" " * 3, "*")
        print(" " * 3, "*")
        print(" " * 3, "*")
    elif digit == 2:
        print(" ", "* " * 3)
        print(" " * 6, "*")
        print(" " * 6, "*")
        print(" " * 6, "*")
        print(" ", "* " * 3)
        print("*")
        print("*")
        print("*")
        print(" ", "* " * 3)
    elif digit == 3:
        print(" ", "* " * 3)
        print(" " * 4, "*")
        print(" " * 4, "*")
        print(" " * 4, "*")
        print(" ", "* " * 3)
        print(" " * 4, "*")
        print(" " * 4, "*")
        print(" " * 4, "*")
        print(" ", "* " * 3)
    elif digit == 4:
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print(" ", "* " * 3)
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" " * 7, "*")
    elif digit == 5:
        print(" ", "* " * 3)
        print("*")
        print("*")
        print("*")
        print(" ", "* " * 3)
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" ", "* " * 3)
    elif digit == 6:
        print(" ", "* " * 3)
        print("*")
        print("*")
        print("*")
        print(" ", "* " * 3)
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print(" ", "* " * 3)
    elif digit == 7:
        print(" ", "* " * 3)
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" " * 7, "*")
        print()
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" " * 7, "*")
    elif digit == 8:
        print(" ", "* " * 3)
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print(" ", "* " * 3)
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print(" ", "* " * 3)
    elif digit == 9:
        print(" ", "* " * 3)
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print("*", " " * 5, "*")
        print(" ", "* " * 3)
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" " * 7, "*")
        print(" ", "* " * 3)

